version: '3.8'

services:
  app-fraud-preventions:
    build:
      context: .
      target: builder
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DB_HOST=db-fraud-preventions
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=fraud_prevention_db
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
    command: python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db-fraud-preventions:
        condition: service_healthy

  db-fraud-preventions:
    image: mysql:8.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fraud_prevention_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    volumes:
      - .dbfraudprevention:/var/lib/mysql:rw
    user: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  dbfraudprevention:
    name: dbfraudprevention