version: '3.8'

services:
  app-fraud-preventions:
    image: ghcr.io/jdramirezl/mkp-fraud-preventions-ms:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db-fraud-preventions
      - DB_PORT=3305
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=fraud_prevention_db
    depends_on:
      db-fraud-preventions:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  db-fraud-preventions:
    image: mysql:8.3
    restart: always
    ports:
      - "3305:3305"
    environment:
      MYSQL_DATABASE: fraud_prevention_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3305
    volumes:
      - .dbfraudprevention:/var/lib/mysql-fraud-prevention:rw
    user: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  fraudprevention:
    name: dbfraudprevention