version: '3.8'

services:
  app-fraud-preventions:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - db-fraud-preventions

  db-fraud-preventions:
    image: mysql:8.3
    restart: always
    ports:
      - "3305:3305"
    environment:
      MYSQL_DATABASE: fraud_prevention_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3305
    volumes:
      - .dbfraudprevention:/var/lib/mysql-fraud-prevention:rw
    user: mysql

volumes:
  fraudprevention:
    name: dbfraudprevention