name: CI/CD Pipeline

on:
  workflow_dispatch:  # Manual trigger
  pull_request:
    paths-ignore:
      - 'terraform/**'
      - '**.md'
      - '.github/workflows/terraform.yml'

env:
  REGION: us-central1
  PROJECT_ID: tonal-unity-460616-s4
  IMAGE_NAME: fraud-prevention-api
  REGISTRY: us-central1-docker.pkg.dev

permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ".[test]"

      - name: Run tests
        run: |
          pytest --cov=src --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          service_account_key_file: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/fraud-prevention/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/fraud-prevention/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export Image Digest
        id: image
        run: |
          echo "image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/fraud-prevention/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}" >> $GITHUB_OUTPUT

  terraform:
    needs: build-and-push
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    env:
      TF_WORKSPACE: "fraud-prevention"
      TF_VAR_project_id: "tonal-unity-460616-s4"
      TF_VAR_region: "us-central1"
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          service_account_key_file: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Get Image Tag
        id: image
        run: |
          echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        working-directory: .

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: |
          # Force unlock if there's a leftover lock
          terraform force-unlock -force 1748029724845896 || true
          
          # Remove any existing local state
          rm -rf .terraform* terraform.tfstate*
          
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.TF_VAR_project_id }}-terraform-state" \
            -backend-config="prefix=fraud-prevention"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        # Only run plan on pull requests
        if: github.event_name == 'pull_request'
        run: |
          # Force unlock if there's a leftover lock
          terraform force-unlock -force 1748029724845896 || true
          
          terraform plan \
            -var="container_image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/fraud-prevention/fraud-prevention-api:${{ steps.image.outputs.tag }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -no-color \
            -input=false \
            -lock=false \
            -detailed-exitcode || exit_code=$?

          if [ "${exit_code}" -eq 1 ]; then
            echo "Terraform Plan Failed!"
            echo "exitcode=${exit_code}" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "exitcode=${exit_code}" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        # Only runs if plan failed
        if: steps.plan.outcome == 'failure' || steps.plan.outputs.exitcode == 1
        run: |
          echo "Terraform Plan Failed. Check the plan output above for errors."
          exit 1

      - name: Terraform Apply
        # Only run apply on push to main branch
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Force unlock if there's a leftover lock
          terraform force-unlock -force 1748029724845896 || true
          
          # Import existing network if it exists
          terraform import google_compute_network.private_network projects/${{ env.PROJECT_ID }}/global/networks/fraud-prevention-network || true
          
          # Import existing service account if it exists
          terraform import google_service_account.cloud_run_service_account projects/${{ env.PROJECT_ID }}/serviceAccounts/cloud-run-service-account@${{ env.PROJECT_ID }}.iam.gserviceaccount.com || true
          
          terraform apply -auto-approve \
            -var="container_image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/fraud-prevention/fraud-prevention-api:${{ steps.image.outputs.tag }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -lock=false
